# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Match Rows Between Two DataFrames with Missing Data
NULL

match_rows <- function(z, x) {
    .Call('_MissCat_match_rows', PACKAGE = 'MissCat', z, x)
}

merge_duplicate_rows_large <- function(df) {
    .Call('_MissCat_merge_duplicate_rows_large', PACKAGE = 'MissCat', df)
}

match_rows_and_add_rowname <- function(A, B) {
    .Call('_MissCat_match_rows_and_add_rowname', PACKAGE = 'MissCat', A, B)
}

supDist <- function(x, y) {
    .Call('_MissCat_supDist', PACKAGE = 'MissCat', x, y)
}

count_compare <- function(x, dat, hasNA) {
    .Call('_MissCat_count_compare', PACKAGE = 'MissCat', x, dat, hasNA)
}

